// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cpd_response.proto

#include "cpd_response.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_cpd_5fresponse_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_cpd_5fresponse_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_ResponseValue;
}  // namespace protobuf_cpd_5fresponse_2eproto
namespace tutorial {
class ResponseValueDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ResponseValue>
      _instance;
} _ResponseValue_default_instance_;
class TouTiaoMultipleResponseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<TouTiaoMultipleResponse>
      _instance;
} _TouTiaoMultipleResponse_default_instance_;
}  // namespace tutorial
namespace protobuf_cpd_5fresponse_2eproto {
static void InitDefaultsResponseValue() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::tutorial::_ResponseValue_default_instance_;
    new (ptr) ::tutorial::ResponseValue();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::tutorial::ResponseValue::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ResponseValue =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsResponseValue}, {}};

static void InitDefaultsTouTiaoMultipleResponse() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::tutorial::_TouTiaoMultipleResponse_default_instance_;
    new (ptr) ::tutorial::TouTiaoMultipleResponse();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::tutorial::TouTiaoMultipleResponse::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_TouTiaoMultipleResponse =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsTouTiaoMultipleResponse}, {
      &protobuf_cpd_5fresponse_2eproto::scc_info_ResponseValue.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_ResponseValue.base);
  ::google::protobuf::internal::InitSCC(&scc_info_TouTiaoMultipleResponse.base);
}

}  // namespace protobuf_cpd_5fresponse_2eproto
namespace tutorial {

// ===================================================================

void ResponseValue::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ResponseValue::kIiFieldNumber;
const int ResponseValue::kCtsFieldNumber;
const int ResponseValue::kCvsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ResponseValue::ResponseValue()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_cpd_5fresponse_2eproto::scc_info_ResponseValue.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:tutorial.ResponseValue)
}
ResponseValue::ResponseValue(const ResponseValue& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL),
      cts_(from.cts_),
      cvs_(from.cvs_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ii_ = from.ii_;
  // @@protoc_insertion_point(copy_constructor:tutorial.ResponseValue)
}

void ResponseValue::SharedCtor() {
  ii_ = 0;
}

ResponseValue::~ResponseValue() {
  // @@protoc_insertion_point(destructor:tutorial.ResponseValue)
  SharedDtor();
}

void ResponseValue::SharedDtor() {
}

void ResponseValue::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ResponseValue& ResponseValue::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_cpd_5fresponse_2eproto::scc_info_ResponseValue.base);
  return *internal_default_instance();
}


void ResponseValue::Clear() {
// @@protoc_insertion_point(message_clear_start:tutorial.ResponseValue)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cts_.Clear();
  cvs_.Clear();
  ii_ = 0;
  _internal_metadata_.Clear();
}

bool ResponseValue::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::LiteUnknownFieldSetter unknown_fields_setter(
      &_internal_metadata_);
  ::google::protobuf::io::StringOutputStream unknown_fields_output(
      unknown_fields_setter.buffer());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_output, false);
  // @@protoc_insertion_point(parse_start:tutorial.ResponseValue)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 ii = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &ii_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated int32 cts = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_cts())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 18u, input, this->mutable_cts())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated int32 cvs = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_cvs())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 26u, input, this->mutable_cvs())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:tutorial.ResponseValue)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:tutorial.ResponseValue)
  return false;
#undef DO_
}

void ResponseValue::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:tutorial.ResponseValue)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 ii = 1;
  if (this->ii() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->ii(), output);
  }

  // repeated int32 cts = 2;
  if (this->cts_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(2, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(static_cast< ::google::protobuf::uint32>(
        _cts_cached_byte_size_));
  }
  for (int i = 0, n = this->cts_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32NoTag(
      this->cts(i), output);
  }

  // repeated int32 cvs = 3;
  if (this->cvs_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(3, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(static_cast< ::google::protobuf::uint32>(
        _cvs_cached_byte_size_));
  }
  for (int i = 0, n = this->cvs_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32NoTag(
      this->cvs(i), output);
  }

  output->WriteRaw((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).data(),
                   static_cast<int>((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size()));
  // @@protoc_insertion_point(serialize_end:tutorial.ResponseValue)
}

size_t ResponseValue::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tutorial.ResponseValue)
  size_t total_size = 0;

  total_size += (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size();

  // repeated int32 cts = 2;
  {
    size_t data_size = ::google::protobuf::internal::WireFormatLite::
      Int32Size(this->cts_);
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
            static_cast< ::google::protobuf::int32>(data_size));
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _cts_cached_byte_size_ = cached_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  // repeated int32 cvs = 3;
  {
    size_t data_size = ::google::protobuf::internal::WireFormatLite::
      Int32Size(this->cvs_);
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
            static_cast< ::google::protobuf::int32>(data_size));
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _cvs_cached_byte_size_ = cached_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  // int32 ii = 1;
  if (this->ii() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->ii());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ResponseValue::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const ResponseValue*>(&from));
}

void ResponseValue::MergeFrom(const ResponseValue& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:tutorial.ResponseValue)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cts_.MergeFrom(from.cts_);
  cvs_.MergeFrom(from.cvs_);
  if (from.ii() != 0) {
    set_ii(from.ii());
  }
}

void ResponseValue::CopyFrom(const ResponseValue& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tutorial.ResponseValue)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ResponseValue::IsInitialized() const {
  return true;
}

void ResponseValue::Swap(ResponseValue* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ResponseValue::InternalSwap(ResponseValue* other) {
  using std::swap;
  cts_.InternalSwap(&other->cts_);
  cvs_.InternalSwap(&other->cvs_);
  swap(ii_, other->ii_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::std::string ResponseValue::GetTypeName() const {
  return "tutorial.ResponseValue";
}


// ===================================================================

void TouTiaoMultipleResponse::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int TouTiaoMultipleResponse::kCodeFieldNumber;
const int TouTiaoMultipleResponse::kValueFieldNumber;
const int TouTiaoMultipleResponse::kVersionFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

TouTiaoMultipleResponse::TouTiaoMultipleResponse()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_cpd_5fresponse_2eproto::scc_info_TouTiaoMultipleResponse.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:tutorial.TouTiaoMultipleResponse)
}
TouTiaoMultipleResponse::TouTiaoMultipleResponse(const TouTiaoMultipleResponse& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL),
      value_(from.value_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  version_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.version().size() > 0) {
    version_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.version_);
  }
  code_ = from.code_;
  // @@protoc_insertion_point(copy_constructor:tutorial.TouTiaoMultipleResponse)
}

void TouTiaoMultipleResponse::SharedCtor() {
  version_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  code_ = 0;
}

TouTiaoMultipleResponse::~TouTiaoMultipleResponse() {
  // @@protoc_insertion_point(destructor:tutorial.TouTiaoMultipleResponse)
  SharedDtor();
}

void TouTiaoMultipleResponse::SharedDtor() {
  version_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void TouTiaoMultipleResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const TouTiaoMultipleResponse& TouTiaoMultipleResponse::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_cpd_5fresponse_2eproto::scc_info_TouTiaoMultipleResponse.base);
  return *internal_default_instance();
}


void TouTiaoMultipleResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:tutorial.TouTiaoMultipleResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  value_.Clear();
  version_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  code_ = 0;
  _internal_metadata_.Clear();
}

bool TouTiaoMultipleResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::LiteUnknownFieldSetter unknown_fields_setter(
      &_internal_metadata_);
  ::google::protobuf::io::StringOutputStream unknown_fields_output(
      unknown_fields_setter.buffer());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_output, false);
  // @@protoc_insertion_point(parse_start:tutorial.TouTiaoMultipleResponse)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 code = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &code_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .tutorial.ResponseValue value = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_value()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string version = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_version()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->version().data(), static_cast<int>(this->version().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "tutorial.TouTiaoMultipleResponse.version"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:tutorial.TouTiaoMultipleResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:tutorial.TouTiaoMultipleResponse)
  return false;
#undef DO_
}

void TouTiaoMultipleResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:tutorial.TouTiaoMultipleResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 code = 1;
  if (this->code() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->code(), output);
  }

  // repeated .tutorial.ResponseValue value = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->value_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      2,
      this->value(static_cast<int>(i)),
      output);
  }

  // string version = 3;
  if (this->version().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->version().data(), static_cast<int>(this->version().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "tutorial.TouTiaoMultipleResponse.version");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->version(), output);
  }

  output->WriteRaw((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).data(),
                   static_cast<int>((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size()));
  // @@protoc_insertion_point(serialize_end:tutorial.TouTiaoMultipleResponse)
}

size_t TouTiaoMultipleResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tutorial.TouTiaoMultipleResponse)
  size_t total_size = 0;

  total_size += (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size();

  // repeated .tutorial.ResponseValue value = 2;
  {
    unsigned int count = static_cast<unsigned int>(this->value_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->value(static_cast<int>(i)));
    }
  }

  // string version = 3;
  if (this->version().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->version());
  }

  // int32 code = 1;
  if (this->code() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->code());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void TouTiaoMultipleResponse::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const TouTiaoMultipleResponse*>(&from));
}

void TouTiaoMultipleResponse::MergeFrom(const TouTiaoMultipleResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:tutorial.TouTiaoMultipleResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  value_.MergeFrom(from.value_);
  if (from.version().size() > 0) {

    version_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.version_);
  }
  if (from.code() != 0) {
    set_code(from.code());
  }
}

void TouTiaoMultipleResponse::CopyFrom(const TouTiaoMultipleResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tutorial.TouTiaoMultipleResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TouTiaoMultipleResponse::IsInitialized() const {
  return true;
}

void TouTiaoMultipleResponse::Swap(TouTiaoMultipleResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void TouTiaoMultipleResponse::InternalSwap(TouTiaoMultipleResponse* other) {
  using std::swap;
  CastToBase(&value_)->InternalSwap(CastToBase(&other->value_));
  version_.Swap(&other->version_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(code_, other->code_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::std::string TouTiaoMultipleResponse::GetTypeName() const {
  return "tutorial.TouTiaoMultipleResponse";
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace tutorial
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::tutorial::ResponseValue* Arena::CreateMaybeMessage< ::tutorial::ResponseValue >(Arena* arena) {
  return Arena::CreateInternal< ::tutorial::ResponseValue >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::tutorial::TouTiaoMultipleResponse* Arena::CreateMaybeMessage< ::tutorial::TouTiaoMultipleResponse >(Arena* arena) {
  return Arena::CreateInternal< ::tutorial::TouTiaoMultipleResponse >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
