// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cpd_response.proto

#ifndef PROTOBUF_INCLUDED_cpd_5fresponse_2eproto
#define PROTOBUF_INCLUDED_cpd_5fresponse_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_cpd_5fresponse_2eproto 

namespace protobuf_cpd_5fresponse_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
}  // namespace protobuf_cpd_5fresponse_2eproto
namespace tutorial {
class ResponseValue;
class ResponseValueDefaultTypeInternal;
extern ResponseValueDefaultTypeInternal _ResponseValue_default_instance_;
class TouTiaoMultipleResponse;
class TouTiaoMultipleResponseDefaultTypeInternal;
extern TouTiaoMultipleResponseDefaultTypeInternal _TouTiaoMultipleResponse_default_instance_;
}  // namespace tutorial
namespace google {
namespace protobuf {
template<> ::tutorial::ResponseValue* Arena::CreateMaybeMessage<::tutorial::ResponseValue>(Arena*);
template<> ::tutorial::TouTiaoMultipleResponse* Arena::CreateMaybeMessage<::tutorial::TouTiaoMultipleResponse>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace tutorial {

// ===================================================================

class ResponseValue : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:tutorial.ResponseValue) */ {
 public:
  ResponseValue();
  virtual ~ResponseValue();

  ResponseValue(const ResponseValue& from);

  inline ResponseValue& operator=(const ResponseValue& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ResponseValue(ResponseValue&& from) noexcept
    : ResponseValue() {
    *this = ::std::move(from);
  }

  inline ResponseValue& operator=(ResponseValue&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ResponseValue& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ResponseValue* internal_default_instance() {
    return reinterpret_cast<const ResponseValue*>(
               &_ResponseValue_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(ResponseValue* other);
  friend void swap(ResponseValue& a, ResponseValue& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ResponseValue* New() const final {
    return CreateMaybeMessage<ResponseValue>(NULL);
  }

  ResponseValue* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ResponseValue>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    final;
  void CopyFrom(const ResponseValue& from);
  void MergeFrom(const ResponseValue& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ResponseValue* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int32 cts = 2;
  int cts_size() const;
  void clear_cts();
  static const int kCtsFieldNumber = 2;
  ::google::protobuf::int32 cts(int index) const;
  void set_cts(int index, ::google::protobuf::int32 value);
  void add_cts(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      cts() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_cts();

  // repeated int32 cvs = 3;
  int cvs_size() const;
  void clear_cvs();
  static const int kCvsFieldNumber = 3;
  ::google::protobuf::int32 cvs(int index) const;
  void set_cvs(int index, ::google::protobuf::int32 value);
  void add_cvs(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      cvs() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_cvs();

  // int32 ii = 1;
  void clear_ii();
  static const int kIiFieldNumber = 1;
  ::google::protobuf::int32 ii() const;
  void set_ii(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:tutorial.ResponseValue)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > cts_;
  mutable int _cts_cached_byte_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > cvs_;
  mutable int _cvs_cached_byte_size_;
  ::google::protobuf::int32 ii_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_cpd_5fresponse_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class TouTiaoMultipleResponse : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:tutorial.TouTiaoMultipleResponse) */ {
 public:
  TouTiaoMultipleResponse();
  virtual ~TouTiaoMultipleResponse();

  TouTiaoMultipleResponse(const TouTiaoMultipleResponse& from);

  inline TouTiaoMultipleResponse& operator=(const TouTiaoMultipleResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  TouTiaoMultipleResponse(TouTiaoMultipleResponse&& from) noexcept
    : TouTiaoMultipleResponse() {
    *this = ::std::move(from);
  }

  inline TouTiaoMultipleResponse& operator=(TouTiaoMultipleResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const TouTiaoMultipleResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TouTiaoMultipleResponse* internal_default_instance() {
    return reinterpret_cast<const TouTiaoMultipleResponse*>(
               &_TouTiaoMultipleResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(TouTiaoMultipleResponse* other);
  friend void swap(TouTiaoMultipleResponse& a, TouTiaoMultipleResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline TouTiaoMultipleResponse* New() const final {
    return CreateMaybeMessage<TouTiaoMultipleResponse>(NULL);
  }

  TouTiaoMultipleResponse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<TouTiaoMultipleResponse>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    final;
  void CopyFrom(const TouTiaoMultipleResponse& from);
  void MergeFrom(const TouTiaoMultipleResponse& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(TouTiaoMultipleResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .tutorial.ResponseValue value = 2;
  int value_size() const;
  void clear_value();
  static const int kValueFieldNumber = 2;
  ::tutorial::ResponseValue* mutable_value(int index);
  ::google::protobuf::RepeatedPtrField< ::tutorial::ResponseValue >*
      mutable_value();
  const ::tutorial::ResponseValue& value(int index) const;
  ::tutorial::ResponseValue* add_value();
  const ::google::protobuf::RepeatedPtrField< ::tutorial::ResponseValue >&
      value() const;

  // string version = 3;
  void clear_version();
  static const int kVersionFieldNumber = 3;
  const ::std::string& version() const;
  void set_version(const ::std::string& value);
  #if LANG_CXX11
  void set_version(::std::string&& value);
  #endif
  void set_version(const char* value);
  void set_version(const char* value, size_t size);
  ::std::string* mutable_version();
  ::std::string* release_version();
  void set_allocated_version(::std::string* version);

  // int32 code = 1;
  void clear_code();
  static const int kCodeFieldNumber = 1;
  ::google::protobuf::int32 code() const;
  void set_code(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:tutorial.TouTiaoMultipleResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::tutorial::ResponseValue > value_;
  ::google::protobuf::internal::ArenaStringPtr version_;
  ::google::protobuf::int32 code_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_cpd_5fresponse_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ResponseValue

// int32 ii = 1;
inline void ResponseValue::clear_ii() {
  ii_ = 0;
}
inline ::google::protobuf::int32 ResponseValue::ii() const {
  // @@protoc_insertion_point(field_get:tutorial.ResponseValue.ii)
  return ii_;
}
inline void ResponseValue::set_ii(::google::protobuf::int32 value) {
  
  ii_ = value;
  // @@protoc_insertion_point(field_set:tutorial.ResponseValue.ii)
}

// repeated int32 cts = 2;
inline int ResponseValue::cts_size() const {
  return cts_.size();
}
inline void ResponseValue::clear_cts() {
  cts_.Clear();
}
inline ::google::protobuf::int32 ResponseValue::cts(int index) const {
  // @@protoc_insertion_point(field_get:tutorial.ResponseValue.cts)
  return cts_.Get(index);
}
inline void ResponseValue::set_cts(int index, ::google::protobuf::int32 value) {
  cts_.Set(index, value);
  // @@protoc_insertion_point(field_set:tutorial.ResponseValue.cts)
}
inline void ResponseValue::add_cts(::google::protobuf::int32 value) {
  cts_.Add(value);
  // @@protoc_insertion_point(field_add:tutorial.ResponseValue.cts)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
ResponseValue::cts() const {
  // @@protoc_insertion_point(field_list:tutorial.ResponseValue.cts)
  return cts_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
ResponseValue::mutable_cts() {
  // @@protoc_insertion_point(field_mutable_list:tutorial.ResponseValue.cts)
  return &cts_;
}

// repeated int32 cvs = 3;
inline int ResponseValue::cvs_size() const {
  return cvs_.size();
}
inline void ResponseValue::clear_cvs() {
  cvs_.Clear();
}
inline ::google::protobuf::int32 ResponseValue::cvs(int index) const {
  // @@protoc_insertion_point(field_get:tutorial.ResponseValue.cvs)
  return cvs_.Get(index);
}
inline void ResponseValue::set_cvs(int index, ::google::protobuf::int32 value) {
  cvs_.Set(index, value);
  // @@protoc_insertion_point(field_set:tutorial.ResponseValue.cvs)
}
inline void ResponseValue::add_cvs(::google::protobuf::int32 value) {
  cvs_.Add(value);
  // @@protoc_insertion_point(field_add:tutorial.ResponseValue.cvs)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
ResponseValue::cvs() const {
  // @@protoc_insertion_point(field_list:tutorial.ResponseValue.cvs)
  return cvs_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
ResponseValue::mutable_cvs() {
  // @@protoc_insertion_point(field_mutable_list:tutorial.ResponseValue.cvs)
  return &cvs_;
}

// -------------------------------------------------------------------

// TouTiaoMultipleResponse

// int32 code = 1;
inline void TouTiaoMultipleResponse::clear_code() {
  code_ = 0;
}
inline ::google::protobuf::int32 TouTiaoMultipleResponse::code() const {
  // @@protoc_insertion_point(field_get:tutorial.TouTiaoMultipleResponse.code)
  return code_;
}
inline void TouTiaoMultipleResponse::set_code(::google::protobuf::int32 value) {
  
  code_ = value;
  // @@protoc_insertion_point(field_set:tutorial.TouTiaoMultipleResponse.code)
}

// repeated .tutorial.ResponseValue value = 2;
inline int TouTiaoMultipleResponse::value_size() const {
  return value_.size();
}
inline void TouTiaoMultipleResponse::clear_value() {
  value_.Clear();
}
inline ::tutorial::ResponseValue* TouTiaoMultipleResponse::mutable_value(int index) {
  // @@protoc_insertion_point(field_mutable:tutorial.TouTiaoMultipleResponse.value)
  return value_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::tutorial::ResponseValue >*
TouTiaoMultipleResponse::mutable_value() {
  // @@protoc_insertion_point(field_mutable_list:tutorial.TouTiaoMultipleResponse.value)
  return &value_;
}
inline const ::tutorial::ResponseValue& TouTiaoMultipleResponse::value(int index) const {
  // @@protoc_insertion_point(field_get:tutorial.TouTiaoMultipleResponse.value)
  return value_.Get(index);
}
inline ::tutorial::ResponseValue* TouTiaoMultipleResponse::add_value() {
  // @@protoc_insertion_point(field_add:tutorial.TouTiaoMultipleResponse.value)
  return value_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::tutorial::ResponseValue >&
TouTiaoMultipleResponse::value() const {
  // @@protoc_insertion_point(field_list:tutorial.TouTiaoMultipleResponse.value)
  return value_;
}

// string version = 3;
inline void TouTiaoMultipleResponse::clear_version() {
  version_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& TouTiaoMultipleResponse::version() const {
  // @@protoc_insertion_point(field_get:tutorial.TouTiaoMultipleResponse.version)
  return version_.GetNoArena();
}
inline void TouTiaoMultipleResponse::set_version(const ::std::string& value) {
  
  version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:tutorial.TouTiaoMultipleResponse.version)
}
#if LANG_CXX11
inline void TouTiaoMultipleResponse::set_version(::std::string&& value) {
  
  version_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:tutorial.TouTiaoMultipleResponse.version)
}
#endif
inline void TouTiaoMultipleResponse::set_version(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:tutorial.TouTiaoMultipleResponse.version)
}
inline void TouTiaoMultipleResponse::set_version(const char* value, size_t size) {
  
  version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:tutorial.TouTiaoMultipleResponse.version)
}
inline ::std::string* TouTiaoMultipleResponse::mutable_version() {
  
  // @@protoc_insertion_point(field_mutable:tutorial.TouTiaoMultipleResponse.version)
  return version_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* TouTiaoMultipleResponse::release_version() {
  // @@protoc_insertion_point(field_release:tutorial.TouTiaoMultipleResponse.version)
  
  return version_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void TouTiaoMultipleResponse::set_allocated_version(::std::string* version) {
  if (version != NULL) {
    
  } else {
    
  }
  version_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), version);
  // @@protoc_insertion_point(field_set_allocated:tutorial.TouTiaoMultipleResponse.version)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace tutorial

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_cpd_5fresponse_2eproto
